### ISSUE TITLE
[BUG] Inconsistent DateTime format in Holdings/Order CSV Export

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#40]
A very rare occurrence, though when a given timestamp for either order creation or modification (or elsewhere in FM?), is exactly on the second (S.000), the timestamp in CSV file does not have the microsecond (.sss) information present.

For instance, if the timestamp for order createAt is `2019-07-30T04:07:03.000`, then the output CSV only includes `2019-07-30T04:07:03`.  

This is inconsistent with the expected date-time format `%Y-%m-%dT%H:%M:%S.%f`

Expected behaviour:  
String for such timestamps should include trailing `.0`

**Comment by JanStureNielsen** [comment]
This is now fixed in FM-3.

**Comment by darkfishy** [comment]
Hey Jan (@JanStureNielsen), Could this fix be backported to FM2? The problem still persists and now another example has surfaced where even the seconds component is missing. This causes major parsing headaches and having to apply hacks.

![screenshot-2022_02_03-00_02_19+1100](https://user-images.githubusercontent.com/19355157/152159087-915075de-3662-4ccb-b4bb-7b62711e9602.png)

**Comment by darkfishy** [comment]
In fact there are multiple occurrences of such dates.

account: rad-prodigy
OID: 14679

**Comment by JanStureNielsen** [comment]
This looks like a pretty easy back-port, @darkfishy -- I'll try it out tonight and provide an update.

**Comment by JanStureNielsen** [comment]
In FM-3, time is stored with microsecond resolution with trailing zeros: 2022-02-07T16:42:52.782520.

**Comment by darkfishy** [comment]
That sounds good Jan. I can test it if/when we transition to FM-3.
Does this correspond to both CSV and JSON endpoints?

**Comment by darkfishy** [comment]
Hey @JanStureNielsen I can confirm that the datetime fields in CSV have microsecond resolution, and likely consistently zero-padded.

However, there still seems to be some discrepancy in the datetime fields that are returned in JSON (via REST/WS). I'll raise it as a separate issue for tracking purposes.

Closing this issue.
